### ISSUE TITLE
gcp-project-init isn't idempotent

### ISSUE THREAD

**Issue by mrtyler** [exekube/exekube#92]
Since I'm already bugging you Ilya :), I wanted to ask your thoughts on this.

`xk gcp-project-init` fails if you run it more than once. It would be nice if it were idempotent, e.g. so I could delete my terraform state bucket and let it get re-created, or so that the default gcloud project would be set to the last environment I touched.

I can provide more context if my use case is unclear. There are some notes in https://issues.gpii.net/browse/GPII-2989.

Do you think idempotence would be a useful improvement for gcp-project-init? Is there a better solution I haven't found yet? Is this an irreconcilable difference between your goals and ours? I would appreciate your thoughts on this if you have a few minutes. :)

**Comment by mrtyler** [comment]
Bump :) and related question:

Have you considered replacing `gcloud` commands in a shell script with Terraform code  for project-init responsibilities? It looks like everything `gcp-project-init` does today can be done (idempotently!) by Terraform except:
* Enabling the serviceusage API (see #90)
* Downloading credentials for the projectowner service account
* Setting the default project in `gcloud` (convenient for interactive use and debugging but the project used by Terraform is configured in the `provider {}` block and one-off `gcloud` commands should probably specify `--project` for explicitness and safety anyway ;)

These one-off commands could be wrapped in `null_resource` as exekube already does with other one-off commands.

Would this be a good direction for exekube? Is there another way to get what we want?

**Comment by ilyasotkov** [comment]
> Have you considered replacing gcloud commands in a shell script with Terraform code for project-init responsibilities?

I indeed have, here's how I used it: https://github.com/exekube/exekube/blob/bfb9abfb4676f1c530901a66b0f2cdd2f7b27e74/modules/gcp-project/main.tf

It works overall, but I decided to forego this solution because we'd need to manage Terraform state for this module somewhere else, and Exekube environments wouldn't be self-contained any more.

`gcp-project-init` is just a bootstrapper script for new Exekube environments. The script is meant to be run only once and all resources it creates would then managed via manually or GCP Console / CLI (`xk gcloud`)

**Comment by mrtyler** [comment]
Thanks for the link. That's a good point about the chicken-and-egg problem for tfstate.

Sounds like your intended use case for gcp-project-init is pretty different from ours, so we'll pursue our own solution and I'll close this issue. Thanks.
